### ISSUE TITLE
Long running operation failed with status Failed

### ISSUE THREAD

**Issue by evanerwee** [MSOpenTech/vagrant-azure#129]
Using Vagrant plugin pre-release 2. Any help as to why I'm getting this error will be really helpful. Using Windows 10.

PS C:\temp>
PS C:\temp> vagrant up --provider=azure
Bringing machine 'default' up with 'azure' provider...
==> default: Preparing SMB shared folders...
    default: You will be asked for the username and password to use for the SMB
    default: folders shortly. Please use the proper username/password of your
    default: Windows account.
    default:
    default: Username: sup
    default: Password (will be hidden):
==> default: Launching an instance with the following settings...
==> default:  -- Management Endpoint: https://management.azure.com
==> default:  -- Subscription Id: e60cbc97-d5f0-4964-b297-c483f189efcf
==> default:  -- Resource Group Name: hidden-river-43
==> default:  -- Location: westus
==> default:  -- VM Name: still-silence-74
==> default:  -- VM Size: Small
==> default:  -- Image URN: canonical:ubuntuserver:16.04.0-DAILY-LTS:latest
==> default:  -- Create or Update of Resource Group: hidden-river-43
==> default: Starting deployment
C:/Users/evan.erwee/.vagrant.d/gems/gems/ms_rest_azure-0.2.3/lib/ms_rest_azure/azure_service_client.rb:72:in `get_long_running_operation_result': { (MsRestAzure::AzureOperationError)
  "message": "Long running operation failed with status Failed",

**Comment by evanerwee** [comment]
I figure out that the default VM Size is invalid. Specific a valid size in the Vagrant file will remove the above error. I specified for example azure.vm_size = 'Standard_A1'

**Comment by scottmmeyer** [comment]
This fixed my issue.

**Comment by devigned** [comment]
This should be fixed in the 2.0.0.pre2 release. Please reopen if it's still an issue.
