### ISSUE TITLE
vagrant-berkshelf and vagrant-omnibus don't seem to work with vagrant-azure

### ISSUE THREAD

**Issue by johnsmyth** [MSOpenTech/vagrant-azure#14]
I'm trying to use chef-solo provisioner with vagrant-azure, but it doesn't seem to work with Vagrant-Omnibus or Vagrant-berkshelf.  When I provision the same vm with virtualbox, it works fine.  Using the azure provider, the other plugins don't appear to get called.

**Comment by jeffmendoza** [comment]
Closing, as #17 was merged
