### ISSUE TITLE
Windows SKU AdminPassword parameter required for Azure RM

### ISSUE THREAD

**Issue by JonosGit** [MSOpenTech/vagrant-azure#143]
Hey there  folks. I have successfully setup the AAD SPN account and I am able to provision Linux SKUs to Azure as needed. I am encountering an issue when attempting to deploy Windows 2012 R2 (below) which looks like a missing parameter for AdminPassword in the ARM template being processed. I have attempted to use the azure.vm_password without any luck. Are there any examples or information for passing this parameter via the Vagrant Azure Plugin?

    "body": "{\"error\":{\"code\":\"InvalidTemplate\",\"message\":\"Deployment template validation failed: 'The value for the template parameter 'adminPassword' at line '1' and column '306' is not provided. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.\"}}",

**Comment by christopher-hirudayasamy** [comment]
Hi @JonosGit  The same issue occurs for me also. Please let me know if you have any solutions?

**Comment by JonosGit** [comment]
Wish I did, this seems to be a vagrant framework issue and blocked my
utilization of vagrant. I did write a tool in Azure PowerShell that does
all the things Vagrant does in Azure (and more) without using ARM templates
(https://github.com/JonosGit/IaaSDeploymentTool) but as far as the vagrant
bits I do not have a work around.

**Comment by AlexZeitler** [comment]
@JonosGit Same here - did you find a solution?

**Comment by matt-richardson** [comment]
I'm also facing this issue. Looks like there's a PR - https://github.com/Azure/vagrant-azure/pull/115 - that looks like it'll make it work, but its sat there since April with no progress...

**Comment by AlexZeitler** [comment]
Looks like the cla has not been signed?

**Comment by matt-richardson** [comment]
Looks like @rysweet is a Microsoft employee anyway. Does the CLA still apply?

**Comment by devigned** [comment]
I believe this can be closed up as of release v2.0.0.pre2.

**Comment by JonosGit** [comment]
Thanks David!

**Comment by devigned** [comment]
@JonosGit, my pleasure. Sorry it took so long. Much thanks to @matt-richardson for the PRs.
