### ISSUE TITLE
Vagrant box add issue 

### ISSUE THREAD

**Issue by mpender** [MSOpenTech/vagrant-azure#153]
vagrant --version 
Vagrant 1.9.1

=====================

vagrant box add azure https://github.com/azure/vagrant-azure/raw/v2.0/dummy.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'azure' (v0) for provider:
    box: Downloading: https://github.com/azure/vagrant-azure/raw/v2.0/dummy.box
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format

On OSX, also present when manually adding the file via : vagrant box add --name azure dummy.box

**Comment by bosconi** [comment]
I'm seeing the exact same thing. Vagrant 1.9.1 (the latest version). Same command and error output.

**Comment by bosconi** [comment]
WORKAROUND BELOW...

The `dummy.box` file seems to be corrupt:

```
jon$ wget https://raw.githubusercontent.com/azure/vagrant-azure/v2.0/dummy.box
--2017-01-29 10:23:48--  https://raw.githubusercontent.com/azure/vagrant-azure/v2.0/dummy.box
Resolving raw.githubusercontent.com... 151.101.40.133
Connecting to raw.githubusercontent.com|151.101.40.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3078 (3.0K) [text/plain]
Saving to: ‘dummy.box’

dummy.box                               100%[===============================================================================>]   3.01K  --.-KB/s    in 0s

2017-01-29 10:23:48 (29.1 MB/s) - ‘dummy.box’ saved [3078/3078]
jon$ tar xzvf dummy.box
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

As a workaround, you can construct your own. From `https://raw.githubusercontent.com/azure/vagrant-azure/v2.0/dummy.box`, copy this section:

```
{
  "provider": "azure"
}
```

into a file named `metadata.json`, and this section:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.provider :azure do |azure|
    azure.vm_size = 'Standard_D1'
  end
end
```

into a file named `Vagrantfile`. Then tar them up:

```
jon$ tar czvf dummy.box metadata.json Vagrantfile
a metadata.json
a Vagrantfile
```

and install the box:

```
jon$ vagrant box add dummy dummy.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'dummy' (v0) for provider:
    box: Unpacking necessary files from: file:///Users/jon/proj/src/github.com/hashicorp/research-paper-lifeguard/azure/debug/dummy.box
==> box: Successfully added box 'dummy' (v0) for 'azure'!
```

It's OK if you already have a box called dummy installed for other providers, as Vagrant distinguishes them.

After this, I was able to bring up an Ubuntu VM using this Vagrantfile: https://gist.github.com/bosconi/49a5e49c76aa0828c84b2de867ace855

(Replace property values in < >, and possibly others, with your values.)

I did see some warnings. This one from `vagrant up`:

```
No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
```

and this from `vagrant ssh`:

```
Enum VirtualMachineSizeTypes does not contain standard_f16, but was received from the server.
```

but I can connect to the VM fine. There's no reason to think they are related, but mentioning for completeness.

**Comment by bosconi** [comment]
Same issue on Ubuntu:

```
jon$ uname -a
Linux ubuntu-1604-vmware 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
jon$ wget https://raw.githubusercontent.com/azure/vagrant-azure/v2.0/dummy.box
--2017-01-30 01:27:45--  https://raw.githubusercontent.com/azure/vagrant-azure/v2.0/dummy.box
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.40.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.40.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3078 (3.0K) [text/plain]
Saving to: ‘dummy.box’

dummy.box                                    100%[==================================================================================================>]   3.01K  --.-KB/s    in 0.001s

2017-01-30 01:27:46 (5.86 MB/s) - ‘dummy.box’ saved [3078/3078]

jon$ tar xzvf dummy.box
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

also happens with `bsdtar` on MacOS and Ubuntu.

**Comment by devigned** [comment]
Fix coming soon: https://github.com/Azure/vagrant-azure/pull/156/files#diff-3d544803677fb519fe9e89b89818f018

**Comment by devigned** [comment]
Should be fixed, now. Please reopen if it's still an issue.
