### ISSUE TITLE
No synced folder implementation is available for your synced folders!

### ISSUE THREAD

**Issue by AwkwardBen** [MSOpenTech/vagrant-azure#154]
The following error message is outputted after _**vagrant up --provider=azure**_ command is executed:

Bringing machine 'default' up with 'azure' provider...
No synced folder implementation is available for your synced folders!
Please consult the documentation to learn why this may be the case.
You may force a synced folder implementation by specifying a "type:"
option for the synced folders. Available synced folder implementations
are listed below.

docker, nfs, rsync, smb, virtualbox

My box file is a custom packer derivation. It has nfs installed and setup to sync an /shome directory. I can view the sync take place when I alter the provision to virtualbox. Does azure use a particular sync method?

**Comment by devigned** [comment]
Depending on your VM OS, I'd either use rsync (*nix) or winrm (windows). I just dropped a change to ensure that rsync is chosen over nfs by default (https://github.com/Azure/vagrant-azure/pull/156/files#diff-f6e9457c8e172deaa1f69f24230572a5R18).

Do you have rsync installed locally?
