### ISSUE TITLE
Support for managed disks

### ISSUE THREAD

**Issue by davidobrien1985** [MSOpenTech/vagrant-azure#157]
Hi,

will this plugin support "managed disks" when they go GA?

Cheers
David

**Comment by devigned** [comment]
Not *exactly* when, but very shortly after. As soon as the Ruby SDK has support, we'll update the base deployment template (https://github.com/Azure/vagrant-azure/blob/v2.0/templates/arm/deployment.json.erb) to use managed disks.

@salameer ☝️

**Comment by davidobrien1985** [comment]
Thanks @devigned !

**Comment by devigned** [comment]
Should be ready to go. See: https://github.com/Azure/vagrant-azure#optional-vm-image-parameters and #190.

**Comment by davidobrien1985** [comment]
Nice work @devigned . Now we just need this also in packer :) https://github.com/mitchellh/packer/issues/4511

**Comment by devigned** [comment]
Thx, man! Might be able to help there. I'll take a look.
