### ISSUE TITLE
Destroy no longer waits for resource group to delete

### ISSUE THREAD

**Issue by matt-richardson** [MSOpenTech/vagrant-azure#158]
Any chance we can revert the [code change](https://github.com/Azure/vagrant-azure/pull/156/files#diff-36a7869a3f13177b92d53eb81ddc1f2fR25) that changed the resource group delete to async? As i'm reusing resource group/vm names, I now need to add my own polling to wait for the delete before I can run it again.

If you dont want to revert, can we stick it behind a config flag?

**Comment by devigned** [comment]
Config seems like a good idea for async delete.
