### ISSUE TITLE
Host must be Windows?

### ISSUE THREAD

**Issue by mattstratton** [MSOpenTech/vagrant-azure#16]
This plugin requires Windows? This is a very limiting factor. It would be much more useful if there was not a dependency on Windows. A few things I see as issues:

1) Not everyone is using Windows as their development machine, especially for this type of work. As a community, people complain all the time when it is assumed that you are using Linux, so this just seems to be a roadblock in adoption.

2) When we want to build automation to use vagrant (in a CI system, for example) we might be using Linux as the OS for the build agent.

**Comment by devigned** [comment]
#44 should now make this possible from *nix host machines as well as Windows machines. The dependency on powershell scripts has been removed.
