### ISSUE TITLE
Can't connect to Vagrant PowerShell or RDP 

### ISSUE THREAD

**Issue by tmintner** [MSOpenTech/vagrant-azure#171]
I am having trouble with the Azure plugin.  It creates the Windows VM and the resource group with all of the correct published ports.  When I try to do a vagrant powershell I am getting “VM must be created before running this command. Run ‘vagrant up’ first.  I run vagrant up —provision and it tells me that the Vm is already running.  If I download the cert to my local machine I can connect to the machine with Enter-pssession and RDP is functioning to the public IP address.

I'm not sure where to start troubleshooting.  The Resource Group is created, the VM is created. I have access to the VM.  I just can't connect with vagrant Powershell or Vagrant RDP

**Comment by tmintner** [comment]
Running a debug on vagrant powershell and vagrant RDP both show it trying to connect to SSH over port 22 and then failing.  Why would it be trying to connect to SSH on a Windows box?

**Comment by devigned** [comment]
It definitely should not be connecting to via SSH. It should be trying to connect via WinRM.

Could you provide your debug output in a gist?

**Comment by tmintner** [comment]
I figured out the issue.  I needed to specify the config.vm.communicator = "winrm"

I ran into other issues as well once I got that figured out.  The Vagrant PowerShell commands do not use the -usessl when running invoke-command and enter-pssession so they will fail when connecting to an Azure VM because you are only allowing the azure VM SSL connectivity.  Also, I had to import the self-signed cert to my machine before it would connect.

I modified the Vagrant code temporarily and imported the cert and was finally able to connect

**Comment by tmintner** [comment]
So specifically the files I had to modify to get the -usessl functioning were the ps.rb under c:\hashicorp\vagrant\embedded\gems\gems\vagrant-1.9.1\plugins\hosts\windows\cap

And
enable_psremoting.ps1 in c:\hashicorp\vagrant\embedded\gems\gems\vagrant-1.9.1\plugins\commands\powershell\scripts

**Comment by devigned** [comment]
I think this should be fixed with the use of custom script extension used in the Windows deployment via `winrm_install_self_signed_cert`.
