### ISSUE TITLE
can't able to connect bosh director using vm public ip or hostname

### ISSUE THREAD

**Issue by abhilash07** [MSOpenTech/vagrant-azure#176]
Hi everyone i recently deployed bosh-lite on azure deployment is successful but i cant able to connect bosh director using vagrant box(bosh-lite vm) public ip. But i can login to vagrant vm using ssh public key.

vagrant version is Vagrant 1.8.3
Vagrant Azure Plugin =  vagrant-azure (2.0.0.pre6)
                                              - Version Constraint: 2.0.0.pre6

Vagrant Deployment

vagrant up --provider=azure
Bringing machine 'default' up with 'azure' provider...
==> default: Launching an instance with the following settings...
==> default:  -- Management Endpoint: https://management.azure.com
==> default:  -- Subscription Id: 63b8241c-249b-4ad5-ab17-0e1c14cdf6ee
==> default:  -- Resource Group Name: nameless-star-7
==> default:  -- Location: KoreaCentral
==> default:  -- Admin Username: vagrant
==> default:  -- VM Name: boshlite
==> default:  -- VM Size: Standard_DS3_v2
==> default:  -- Image URN: canonical:ubuntuserver:16.04-LTS:latest
==> default:  -- DNS Label Prefix: billowing-brook-43
==> default:  -- Create or Update of Resource Group: nameless-star-7
==> default:  -- Starting deployment
==> default:  -- Finished deploying
==> default: Waiting for SSH to become available...
==> default: Machine is booted and ready for use!
==> default: Rsyncing folder: /media/ubuntu/ubuntu/azure/v253/Bosh-Lite/ => /vagrant

Vm Login

ssh -i ~/.ssh/id_rsa.pub vagrant@mypublicip
The authenticity of host 'mypublicip (mypublicip)' can't be established.
ECDSA key fingerprint is SHA256:WIOZrSIUrm+yepyFbz33TDlLzOo2E6mATl5ll5iL038.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'mypublicip' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-66-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.

vagrant@boshlite:~$ exit

bosh target error

bosh target https://mypublicip:25555
[WARNING] cannot access director, trying 4 more times...
[WARNING] cannot access director, trying 3 more times...
[WARNING] cannot access director, trying 2 more times...
[WARNING] cannot access director, trying 1 more times...
cannot access director (execution expired)

And finally when i go into vm azure portal i am seeing this error, saying that

1) Connection is disabled becuase this is not a windows virtual machine

2) OS disk (Disk Size unavailable)

My vagrant config

Vagrant.configure('2') do |config|
  config.vm.box = 'azure'

  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.provider :azure do |azure, override|

    azure.vm_image_urn = 'canonical:ubuntuserver:16.04-LTS:latest'
    azure.vm_name = 'boshlite'   

    azure.tenant_id = 'xxxxxxxxxxxxxxxxxxx' 
    azure.client_id = 'xxxxxxxxxxxxxxxxxxxxxx'
    azure.client_secret = 'innovation'
    azure.subscription_id = 'xxxxxxxxxxxxxxxxxx'
    azure.location = 'KoreaCentral'
    #azure.resource_group_name = 'innovation'    
    azure.vm_size = 'Standard_DS3_v2'

  end

end

Thanks in advance

Regards
Abhilash S

**Comment by devigned** [comment]
I must first say that I know very little about the network configuration bosh-lite needs to run, but the first thing that comes to mind, based on your output here, is that I don't see anything opening up port 25555 on your public ip. You might need to open up that port using `tcp_endpoints`. See the readme optional section: https://github.com/Azure/vagrant-azure#optional for usage info.

**Comment by abhilash07** [comment]
Hi thanks for your response as i think if we open these port in bosh-lite security group is morethan enough. Any how i mention tcp ports in Vagrant file as well and redeployed the same error is coming p again.

Vagrant File 

Vagrant.configure('2') do |config|
  config.vm.box = 'azure'

  # use local ssh key to connect to remote vagrant box
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.provider :azure do |azure, override|

    azure.vm_image_urn = 'canonical:ubuntuserver:16.04-LTS:latest'
    azure.vm_name = 'boshlite'   

    # use Azure Active Directory Application / Service Principal to connect to Azure
    # see: https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/

    # each of the below values will default to use the env vars named as below if not specified explicitly

    azure.tenant_id = 'xxxxxxxxxxxxxxxxxxx' 
    azure.client_id = 'xxxxxxxxxxxxxxxxxxxxxx'
    azure.client_secret = 'innovation'
    azure.subscription_id = 'xxxxxxxxxxxxxxxxxx'
    azure.location = 'KoreaCentral'
    azure.tcp_endpoints = ['1-65535', '3389-53389', 25555]    
    azure.vm_size = 'Standard_DS3_v2'

  end

end

I think azure bosh-lite deployed by vagrant is need more testing by azure team.

Error 

bosh target https://mypublicip:25555
[WARNING] cannot access director, trying 4 more times...
[WARNING] cannot access director, trying 3 more times...
[WARNING] cannot access director, trying 2 more times...
[WARNING] cannot access director, trying 1 more times...
cannot access director (Connection refused - connect(2) for "mypublicip" port 25555 (mypublicip:25555))

Security Group Rules for bosh-lite

![rsz_screenshot_from_2017-03-23_09-03-07](https://cloud.githubusercontent.com/assets/10971841/24226118/ef3ca624-0fa7-11e7-9206-d5abcc15a9c5.png)


Please Look this image from Bosh-lite Diagram 

![bosh-lite](https://cloud.githubusercontent.com/assets/10971841/24226739/8db20fda-0fab-11e7-8bdb-018b529431f6.png)

**Comment by devigned** [comment]
Are you replacing `mypublicip` in the script below with your actual public IP, or are you expecting there's a host entry for `mypublicip`? I had assumed that you were using `mypublicip` as a placeholder for your actual public IP.

```
bosh target https://mypublicip:25555
[WARNING] cannot access director, trying 4 more times...
[WARNING] cannot access director, trying 3 more times...
[WARNING] cannot access director, trying 2 more times...
[WARNING] cannot access director, trying 1 more times...
cannot access director (Connection refused - connect(2) for "mypublicip" port 25555 (mypublicip:25555))
```

**Comment by abhilash07** [comment]
yes of course, i place public IP and trying to connect bosh-lite director but cant it. Moreover there are man errors to fix in azure vagrant plugin too. i deployed bosh-init on azure successfully and deployed cloud foundry. But i don't know what's wrong with bosh-lite.

**Comment by devigned** [comment]
Please expand on "man errors". It's very difficult to help when there is little detail.

**Comment by devigned** [comment]
I'm closing this in favor of tracking this issue: https://github.com/Azure/vagrant-azure/issues/178. We'll add some documentation for how to spin up BOSH.
