### ISSUE TITLE
delete all my resources in my azure after deleting bosh-lite vm in my account

### ISSUE THREAD

**Issue by abhilash07** [MSOpenTech/vagrant-azure#177]
hi everyone today i encounter very serious problem, a after deploying bosh-lite on my azure account i see some connection problems to connect to director on vagrant box. so i delete bosh-lite vm unexpectedly all my resources (virtual networks, subnets, security groups, vms, route tables what not everything ) is disappear(deleted). I dont know the reason

**Comment by devigned** [comment]
This is a duplicate of #132. I'm going to close this issue and track as part of #132.

This has surprised more than a few people. We'll change this behavior in the next preview release.
