### ISSUE TITLE
Add capability to use custom VM image

### ISSUE THREAD

**Issue by joe4dev** [MSOpenTech/vagrant-azure#187]
Currently, `vm_image_urn` (parsed [here](https://github.com/Azure/vagrant-azure/blob/v2.0/lib/vagrant-azure/action/run_instance.rb#L73)) only supports official VM images.

It should be possible to use custom VM images (e.g., created following these instructions for Linux https://docs.microsoft.com/en-us/azure/virtual-machines/linux/capture-image).

It looks like this feature is already worked on here: https://github.com/devigned/vagrant-azure/tree/storage-refactor#optional-image-parameters (using an [image uri](https://github.com/devigned/vagrant-azure/commit/5209a83ee27cf44973fbccc674bdfd352d518547#diff-27f545393ba251eadabbd6863ea5c74bR10))

**Comment by devigned** [comment]
Almost done: https://github.com/Azure/vagrant-azure/compare/v2.0...devigned:storage-refactor?expand=1. I'm hoping to get this into a preview release this week.

**Comment by joe4dev** [comment]
Great news 👍

Trying out the latest version yesterday (https://github.com/devigned/vagrant-azure/commit/297ae590dc8e3fdd13ad6a3da3d003d1b9b4b3be), I ran into the following issue:
```
"body": "{\"status\":\"Failed\",\"error\":{\"code\":\"DeploymentFailed\",\"message\":\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\"details\":[{\"code\":\"BadRequest\",\"message\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"AccountPropertyIsInvalid\\\",\\r\\n    \\\"message\\\": \\\"Account property accountType is invalid for the request.\\\"\\r\\n  }\\r\\n}\"}]}}"
```
It looked like `templates/arm/resources/storage_account.json.erb` was malformed.

Shouldn't it look alike this according to https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts ?
```json
{
  "name": "[variables('storageAccountName')]",
  "type": "Microsoft.Storage/storageAccounts",
  "apiVersion": "2016-12-01",
  "sku": {
    "name": "[parameters('storageAccountType')]"
  },
  "kind": "Storage",
  "location": "[variables('location')]",
  "tags": {},
  "properties": {
  }
}
```
Notice:
* `storageAccountType` is a parameter and not a variable: `"[parameters('storageAccountType')]"`
* `accountType` (e.g., Standard_LRS or Premium_LRS) got renamed to "sku" { "name": ... } according to https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts#Sku

**Comment by devigned** [comment]
Thank you for sharing your finding. That is true. I think I broke it in one of the commits. 

As an aside, with the managed disk work, we don't need to make a storage account. Check out the latest commit to that branch. I think you'll see how that's evolved.

**Comment by devigned** [comment]
Should have landed in https://github.com/Azure/vagrant-azure/pull/190. I'm going to close this issue.

If you find bugs, please don't hesitate to open an issue.
