### ISSUE TITLE
cannot login Windows VM without password reset

### ISSUE THREAD

**Issue by HrsYsn** [MSOpenTech/vagrant-azure#199]
Hi,

I had tried to provision Windows VM by following setting as much as possible with the sample of readme.
![image](https://user-images.githubusercontent.com/1956315/29704107-4ce34906-89b3-11e7-9440-f7bffb2354ab.png)

And provisioning succeeded.
![image](https://user-images.githubusercontent.com/1956315/29704090-3bfb1f60-89b3-11e7-8981-4297b4545ba2.png)

But then I tried to connect the VM by rdp, I could not login with the ID and password I set.
When I reset the password from Azure Portal, I got a connection.

Is this a expected behavior?

**Comment by matt-richardson** [comment]
Try setting `azure.admin_password` as well.
(Not sure if it is required as well, or instead of `azure.vm_password`.)

**Comment by wuftymerguftyguff** [comment]
Same symptoms here too.  WinRM fails to connect, so vagrant configured password never gets set.  Only way to gain access is by resetting password via the portal.

**Comment by HrsYsn** [comment]
Sorry for the late reply.
By adding  `azure.admin_password = "XXX"`, I could set password.
And without `azure.vm_password = "XXX"`, I could deploy and login widnows server.

There is a reply saying that it does not go well, but I would like to close.
