### ISSUE TITLE
rsync error.  you must have a tty to run sudo

### ISSUE THREAD

**Issue by rrkulkarnise** [MSOpenTech/vagrant-azure#21]
I am running vagrant 1.6.2 on Centos 6.5.
I have following in my vagrantfile.

    config.ssh.pty = true
    config.vm.synced_folder "/vagrant", "/vagrant", disabled: false

I am getting following error.

sudo: sorry, you must have a tty to run sudo
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]

Is there a workaround?

Thanks

**Comment by jeffmendoza** [comment]
see posted issue above
