### ISSUE TITLE
How to fill azure.mgmt_certificate var

### ISSUE THREAD

**Issue by pollosp** [MSOpenTech/vagrant-azure#24]
I am trying to manage the vagrant Azure provider from windows, but in the example isn´t clear what type of certificate is needed (CRT,PFX,CER) and If have to fill   azure.mgmt_certificate = 'YOUR AZURE MANAGEMENT CERTIFICATE' var with the path to the certificate o with the cert file content.

Please, can you clarify it? 
And can be usefull if you describe into the doc how to make the cert with windows, linux and OSX (this is into this forum)
Thanks :)

**Comment by jeffmendoza** [comment]
readme enhancement
