### ISSUE TITLE
Certificate management

### ISSUE THREAD

**Issue by pollosp** [MSOpenTech/vagrant-azure#25]
If Iaunch vagrant up --provider=azure using PFX cert as azure.mgmt_certificate I get this error:
C:\Users\olopez\vagrant_getting_started>vagrant up --provider=azure
Bringing machine 'default' up with 'azure' provider...
C:/Users/olopez/.vagrant.d/gems/gems/azure-0.6.3/lib/azure/base_management/base_
management_service.rb:49:in `rescue in initialize': Management certificate not v
alid. Error: PKCS12_parse: mac verify failure (RuntimeError)
        from C:/Users/olopez/.vagrant.d/gems/gems/azure-0.6.3/lib/azure/base_man

If I export this certificate with openssl pkcs12 -in vagrant.pfx -out a.pem  (with passphrase) it work, but it ask for the passphrase in everycommand submited to Azure (a little bit anoying) if I export the certificate with openssl pkcs12 -in vagrant.pfx -out c.pem  -nodes it works.

In the documentation azure.mgmt_certificate  is not clear defined, you dont know if you have to fill it with the pem content or with the path to it.
 
Thanks, good work guys.

**Comment by shield007** [comment]
I have this problem as well. I'm using vagrant 1.7.2. I've tested on a clean centos, ubuntu 14.04 and ubuntu 14.10 boxes as it looks to be a openssl issue.

The azure plugin is:
vagrant-azure (1.1.0)

When I usse the command "vagrant up --provider=azure",  I get the following error:
/home/user/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/base_management/base_management_service.rb:48:in `rescue in initialize': Management certificate not valid. Error: PKCS12_parse: invalid null pkcs12 pointer (RuntimeError)
        from /home/user/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/base_management/base_management_service.rb:35:in `initialize'
        from /home/user/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:22:in `initialize'
        from /home/user/.vagrant.d/gems/gems/vagrant-azure-1.1.0/lib/vagrant-azure/action/connect_azure.rb:41:in `new'
        from /home/user/.vagrant.d/gems/gems/vagrant-azure-1.1.0/lib/vagrant-azure/action/connect_azure.rb:41:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
        from /home/user/.vagrant.d/gems/gems/vagrant-azure-1.1.0/lib/vagrant-azure/provider.rb:58:in `state'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:480:in `state'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:141:in `initialize'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:75:in `new'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:75:in `machine'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:614:in `machine'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/command.rb:74:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:277:in `block (2 levels) in batch'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:275:in `tap'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:275:in `block in batch'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:274:in `synchronize'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:274:in `batch'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/command.rb:58:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
        from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'

**Comment by gionn** [comment]
Your problem doesn't seems to be related to the one reported in this issue, look at the error message.

You should probably open another issue.

**Comment by jeffmendoza** [comment]
We could use a readme update here.

**Comment by lodotek** [comment]
I too am having the same issue. Documentation should be updated to include details about usage of  azure.mgmt_certificate=

**Comment by pawelsawicz** [comment]
any luck ? I think ti's still occurring.
azure.mgmt_certificate require .pem or pfx but in all docs says that management cert shouldn be generated with private key, so file has extension .cer any ideas ?

**Comment by devigned** [comment]
Ok, I'm sorry. I have not update to the latest bits in the azure sdk. This weekend I'll push out an update.

**Comment by DraconPern** [comment]
I have the same issue.  I have tried copying the certificate from publishsettings and paste it into Vagrantfile. I have installed the azure gem but don't get the pfxer command.  I have tried putting the cert into a cert.pfx and set the string to the filename.   I have tried importing the cert.pfx..   And what is "can be supplied as a cert parameter for Service Management Commands"?
