### ISSUE TITLE
Loop into ==> default: Looking for 22

### ISSUE THREAD

**Issue by pollosp** [MSOpenTech/vagrant-azure#27]
Hello again,
When I´m trying to deploy an Windows image with the following lines commented in the vagrantfile:
    #    azure.ssh_private_key_file = 'PATH TO YOUR KEY FILE'
    #    azure.ssh_certificate_file = 'PATH TO YOUR CERTIFICATE FILE'

        # Provide the following values if creating a *Nix VM
     #   azure.ssh_port = 'A VALID PUBLIC PORT'

        # Provide the following values if creating a Windows VM

The plugin falls into a loop, looking for port  TCP 22/SSH port:
==> default: Looking for 22
==> default: Looking for 22
==> default: Looking for 22

It has to test Winrm ports instead SSH ports.

Thanks again.

**Comment by devigned** [comment]
@pollosp the winrm stuff has been reworked in vagrant-azure 1.1.0, can you let us know if this is still an issue?
