### ISSUE TITLE
vagrant + azure :: create new virtual machine problem

### ISSUE THREAD

**Issue by juan-rojas** [MSOpenTech/vagrant-azure#32]
Hi, Im trying to use vagrant+azure. 
I've managed to use vagrant to "power up" an existing machine in the azure environment; but my problem is that I can not create a new virtual box based upon an existing image.

Im using https://github.com/MSOpenTech/vagrant-azure to make the conection between vagrant and azure.

When I run the "vagrant up --provider=azure" command, it ends with an error saying:

"The virtual machine image source is not valid."

The name of the image Im using is an image that I created from a virtual that I'd created using the azure stock librery.

Here is the vagrant file Im using:

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = 'azure2'

	config.vm.provider :azure do |azure|
        azure.mgmt_certificate = 'c:\my.pem'
        azure.mgmt_endpoint = 'https://management.core.windows.net'
        azure.subscription_id = '*******-****-****-****************'
        azure.storage_acct_name = '' # optional. A new one will be generated if not provided.

        azure.vm_image = 'HERE_I_WANT_TO_PUT_THE_NAME_OF_THE_IMAGE_I_D_CREATED'
        azure.vm_user = '***' # defaults to 'vagrant' if not provided
        azure.vm_password = '***' # min 8 characters. should contain a lower case letter, an uppercase letter, a number and a special character

        azure.vm_name = 'HERE_I_WANT_TO_PUT_THE_NAME_OF_THE_NEW_VM' 
        azure.cloud_service_name = 'test01jc' # same as vm_name. leave blank to auto-generate
        azure.deployment_name = 'test01jc' # defaults to cloud_service_name
        azure.vm_location = 'East US' # e.g., West US, Este de EE. UU.
        azure.ssh_private_key_file = ''
        azure.ssh_certificate_file = ''

        # Provide the following values if creating a *Nix VM
        azure.ssh_port = ''

        # Provide the following values if creating a Windows VM
        azure.winrm_transport = [ 'http', 'https' ] # this will open up winrm ports on both http (5985) and http (5986) ports
        # azure.winrm_https_port = 'A VALID PUBLIC PORT' # customize the winrm https port, instead of 5986
        # azure.winrm_http_port = 'A VALID PUBLIC PORT' # customize the winrm http port, insted of 5985

        azure.tcp_endpoints = '3389:53389' # opens the Remote Desktop internal port that listens on public port 53389. Without this, you cannot RDP to a Windows VM.
    end
	
    config.ssh.username = '***' # the one used to create the VM
    config.ssh.password = '***' # the one used to create the VM
end

And this is the command Im using to start everithing up:

vagrant init dumy-box-created
(move to folder and update vagrantfile with the content pasted above)
vagrant up --provider=azure

Please let me know if there is any other information that you keed

Rgds, Jc

**Comment by jeffmendoza** [comment]
Not sure if the ruby sdk can get the custom images yet (see the above reference). It will start working whenever the sdk is updated.

**Comment by err0** [comment]
Here is the issue on the ruby-sdk repo: https://github.com/Azure/azure-sdk-for-ruby/issues/145

**Comment by gothma** [comment]
azure-sdk-for-ruby has [released](https://github.com/Azure/azure-sdk-for-ruby/releases/tag/v0.7.0.pre) the user-image feature. Will this now be reopened?
