### ISSUE TITLE
Pass in a virtual network as azure.vm_virtual_network

### ISSUE THREAD

**Issue by jamesrenfro** [MSOpenTech/vagrant-azure#47]
It looks to me like it's not currently possible to pass in the virtual network name... is that correct? I'm hoping for something like the following:

azure.vm_location = 'West US'
azure.vm_virtual_network_name = 'myExistingVN'

I'm not a Ruby dev, but it looks like editing /vagrant-azure/lib/vagrant-azure/action/run_instance.rb slightly to add the following would be enough.  

     options[:vm_virtual_network_name] = config.vm_virtual_network_name unless \
     config.vm_virtual_network_name.nil?

Do you want a pull request for this?

**Comment by jeffmendoza** [comment]
Yes, that would be great.

**Comment by sepiroth887** [comment]
can we add the subnet inside that network as well? That would be awesome!

**Comment by devigned** [comment]
Closing this ticket and moving @sepiroth887 request for subnets to a new enhancement issue.
