### ISSUE TITLE
Error: PKCS12_parse: invalid null pkcs12 pointer 

### ISSUE THREAD

**Issue by shield007** [MSOpenTech/vagrant-azure#55]
I'm trying to use vagrant from Linux to create and provision a VM, but I can't get it to connect to our azure subscription. I'm using vagrant 1.7.2. I've tested on a clean centos, ubuntu 14.04 and ubuntu 14.10 boxes as it looks to be a openssl issue.

The azure plugin is:
vagrant-azure (1.1.0)

When I use the command "vagrant up --provider=azure", I get the following error:
/home/user/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/base_management/base_management_service.rb:48:in rescue in initialize': Management certificate not valid. Error: PKCS12_parse: invalid null pkcs12 pointer (RuntimeError) from /home/user/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/base_management/base_management_service.rb:35:ininitialize'
from /home/user/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:22:in initialize' from /home/user/.vagrant.d/gems/gems/vagrant-azure-1.1.0/lib/vagrant-azure/action/connect_azure.rb:41:innew'
from /home/user/.vagrant.d/gems/gems/vagrant-azure-1.1.0/lib/vagrant-azure/action/connect_azure.rb:41:in call' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:incall'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in call' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:incall'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in call' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:inblock in run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in busy' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:inrun'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in action_raw' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:inblock in action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in lock' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:incall'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in action' from /home/user/.vagrant.d/gems/gems/vagrant-azure-1.1.0/lib/vagrant-azure/provider.rb:58:instate'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:480:in state' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:141:ininitialize'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:75:in new' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:75:inmachine'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:614:in machine' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:168:inblock in with_target_vms'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in call' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:inblock in with_target_vms'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in each' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:inwith_target_vms'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/command.rb:74:in block in execute' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:277:inblock (2 levels) in batch'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:275:in tap' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:275:inblock in batch'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:274:in synchronize' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:274:inbatch'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/command.rb:58:in execute' from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:inexecute'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in cli' from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in'

I'm pretty sure the cert should be valid, I've generated using various instructions found on the web. All produces same result.

**Comment by CodingStudios** [comment]
I am having the same issue. The certificate is valid and has been uploaded to the management portal. The management portal requires a crt file and not a pem or pfx.

**Comment by CodingStudios** [comment]
I have also tried following the articles below. These return ForbiddenError : The server failed to authenticate the request.

http://blogs.msdn.com/b/cclayton/archive/2012/03/21/windows-azure-and-x509-certificates.aspx
https://github.com/Azure/azure-sdk-for-ruby#useful-commands-for-certificate-operations

**Comment by CodingStudios** [comment]
I used the azure sdk cli to import the build settings file and then exported the cert. This created a pem file and worked in the vagrant config.

https://github.com/Azure/azure-xplat-cli

**Comment by devigned** [comment]
@shield007 vagrant-azure expects you to use a .pem management certificate like so:

```ruby
Vagrant.configure('2') do |config|
	config.vm.box = 'azure'

	config.vm.provider :azure do |azure|
		azure.mgmt_certificate = "#{file_location_of_your_dot_pem}"
```

If you have the .cer you uploaded to the azure portal, then you should be able to do the following: 

`openssl x509 -inform der -in certificate.cer -out certificate.pem`

Let me know if this helps.

**Comment by shield007** [comment]
Ah, the problem was that I did not realise it needed a .pem file. Once I switched to using a pem I got past this problem. I think I was using the .crt before or the .key.

The error and command line help did not really give me a clue that I needed a .pem, so maybe the they could be updated to help others?

**Comment by devigned** [comment]
added this to the readme
