### ISSUE TITLE
Provision with puppet is broken

### ISSUE THREAD

**Issue by zeitiger** [MSOpenTech/vagrant-azure#60]
I use puppet as provision tool and it failed in reference to 
lib/vagrant-azure/action/provision.rb that the constant VagrantPlugins::WinAzure::Provisioner is undefined.
I hot patch it local with a simple 
require 'vagrant-azure/provisioner/puppet.rb' at the beginning of this file. 

I believe following commit could be the reason for this
https://github.com/MSOpenTech/vagrant-azure/commit/aca811252b8981f2f54e7d783c5b399607230c6e#commitcomment-9741851

Could somebody confirm this issue?

**Comment by devigned** [comment]
@zeitiger, confirmed. The vagrant-azure specific provisioner was deprecated, but that obviously was missed. I'll take a look at this.

**Comment by devigned** [comment]
@zeitiger please check out #62 when you have a minute. I think that PR should solve your issue.

**Comment by zeitiger** [comment]
Thanks for the quick response and bugfix.
Looking good, it works and now I get immediate puppet output (before I must wait until puppet finished)

**Comment by zeitiger** [comment]
After some testing around I could watch following behavior:
Long running 'puppet apply' via vagrant disconnect after time from my local shell. I observe remote on the windows vm that the puppet process finished complete.

As I understand you, the vagrant-azure plugin rely on the default vagrant provisioning. Correct?
