### ISSUE TITLE
Azure Certificate Issue

### ISSUE THREAD

**Issue by jonathanmhamilton** [MSOpenTech/vagrant-azure#65]
Hello,

I am stuck with an Azure certificate issue & not sure if I have a legitimate issue or if just user error.  If this is the wrong "forum" then please just redirect me.

My use case is I have SW running inside Docker containers.  I want one Vagrantfile that will let me provision VMs on local PC, AWS & Azure & then start the containers in the new VMs.  Right now I have the first two working with Vagrant, but can't seem to get the Azure one working.  

I am stuck on a certificate issue... have tried multiple times to generate & rerun, but the console output is cryptic.
```
C:\Users\jonathan.m.hamilton\Desktop\Docker\Play\Azure>vagrant up --provider=azu
re
C:/Users/jonathan.m.hamilton/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/base_man
agement/base_management_service.rb:48:in `rescue in initialize': Management cert
ificate not valid. Error: Neither PUB key nor PRIV key: nested asn1 error (Runti
meError)
        from C:/Users/jonathan.m.hamilton/.vagrant.d/gems/gems/azure-0.6.4/lib/a
zure/base_management/base_management_service.rb:35:in `initialize'
```

I ran the following steps... user error or defect?  Thanks in advance!

1. $ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout myPrivateKey.key -out myCert.pem
2. $ openssl  x509 -outform der -in myCert.pem -out myCert.cer
3. Successfully uploaded myCert.cer to Azure Management Console
4. Created Vagrantfile (key lines included only)
Vagrant.configure(2) do |config|
config.vm.box = 'azure'

    config.vm.provider :azure do |azure|
      azure.mgmt_certificate = 'C:\Users\jonathan.m.hamilton\Desktop\Docker\Play\Azure\myCert.pem'
      azure.private_key_file = 'C:\Users\jonathan.m.hamilton\Desktop\Docker\Play\Azure\myPrivateKey.key'
      azure.certificate_file = 'C:\Users\jonathan.m.hamilton\Desktop\Docker\Play\Azure\myCert.cer'

    end
end

**Comment by devigned** [comment]
Hmm... I think your `myCert.pem` only contains the public side of the management cert.

Please run `cat  myCert.pem myPrivateKey.key > mgmt_certificate.pem`. Then set your azure.mgmt_certificate = {location of mgmt_certificate.pem}.

If you `cat mgmt_certificate.pem`, you should see:

-----BEGIN CERTIFICATE-----
{pub key}
-----END CERTIFICATE-----
-----BEGIN RSA PRIVATE KEY-----
{private key}
-----END RSA PRIVATE KEY-----

**Comment by jonathanmhamilton** [comment]
Thanks so much!  That was it!  I still get some sort of provisioning error, but I can close this and research it... cheers!

```
C:\Users\jonathan.m.hamilton\Desktop\Docker\Play\Azure>vagrant up --provider=azu
re
==> default: Attempting to read state for aswpoc1 in aswpoc1-service-jwkqr
Bringing machine 'default' up with 'azure' provider...
==> default: Attempting to read state for aswpoc1 in aswpoc1-service-jwkqr
==> default: Determining OS Type By Image
==> default: OS Type is Linux
==> default: Attempting to read state for aswpoc1 in aswpoc1-service-jwkqr
==> default: {:vm_name=>"aswpoc1", :vm_user=>"vagrant", :image=>"b39f27a8b8c64d5
2b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20140927-en-us-30GB", :passwo
rd=>"masked", :location=>"Central US"}
==> default: {:cloud_service_name=>"aswpoc1-service-jwkqr", :storage_account_nam
e=>"aswpoc1storagesffgg", :private_key_file=>"C:\\Users\\jonathan.m.hamilton\\De
sktop\\Docker\\Play\\Azure\\myPrivateKey.key", :certificate_file=>"C:\\Users\\jo
nathan.m.hamilton\\Desktop\\Docker\\Play\\Azure\\myCert.cer", :ssh_port=>"22", :
vm_size=>"Small"}
ResourceNotFound : The hosted service does not exist.
==> default: Add Role? - false
not enough data
Server not created. Error is: not enough data
```

**Comment by twatson83** [comment]
Hi Skelethan,

Im currently getting the same error as you did (Server not created. Error is: not enough data), did you manage to fix it?

**Comment by skelethan** [comment]
Hi Tim,  Unfortunately I did not ever get this resolved.  I haven't had a chance to come back to it either.  I'm pasting my scrubbed Vagrantfile in case it's helpful

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = 'azure'

    config.vm.provider :azure do |azure|
      azure.mgmt_certificate = 'C:\Users\jonathan.m.hamilton\Desktop\Docker\Play\Azure\mgmt_certificate.pem'
      azure.mgmt_endpoint = 'https://management.core.windows.net'
      azure.subscription_id = '<subscription_id'
      azure.storage_acct_name = '<storage_name>' # optional. A new one will be generated if not provided.

      #azure.vm_image = '5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-65-20140926'
      #azure.vm_image = 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20140927-en-us-30GB'
      azure.vm_image = 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20150123-en-us-30GB'
      azure.vm_user = '<username>' # defaults to 'vagrant' if not provided
      azure.vm_password = '<userpwd>' # min 8 characters. should contain a lower case letter, an uppercase letter, a number and a special character

      azure.vm_name = '<vm_name>' # max 15 characters. contains letters, number and hyphens. can start with letters and can end with letters and numbers
      azure.cloud_service_name = '<service_name>' # same as vm_name. leave blank to auto-generate
      #azure.deployment_name = '<deployname>' # defaults to cloud_service_name
      azure.vm_location = 'West US' # e.g., West US
      azure.private_key_file = 'C:\Vagrant\Azure\myPrivateKey.key'
      azure.certificate_file = 'C:\Vagrant\Azure\myCert.cer'

      # Provide the following values if creating a *Nix VM
      azure.ssh_port = '22'
      # Open HTTP port
      #azure.tcp_endpoints = '80,8000'
    end

  config.ssh.username = '<username>' # the one used to create the VM
  config.ssh.password = '<userpwd>' # the one used to create the VM
end
```
