### ISSUE TITLE
Release Provisioner Exception Bug Fixes

### ISSUE THREAD

**Issue by JonathanPorta** [MSOpenTech/vagrant-azure#66]
Hello,

First off, thanks for writing this plugin for Vagrant. It was the deciding factor to start using Azure. :+1: 

I am using the Chef provisioner from Vagrant, but it is throwing the following exception:

```.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/provision.rb:28:in `run_provisioner': uninitialized constant VagrantPlugins::WinAzure::Provisioner (NameError)```

I looked around the commit history and found a [PR][1] that appears to fix this issue. It looks like these commits didn't make into the last release in February.

Would you mind cutting a new release that includes the commits for this bug fix? I am sure you guys already have a plan for the next release, but I just thought I'd give you a nudge. ;)

Thanks again for the great plugin!

[1]: https://github.com/MSOpenTech/vagrant-azure/pull/62

**Comment by devigned** [comment]
This has been merged into master and will be distributed in the next release. Please verify that master fixes your problem.

**Comment by devigned** [comment]
v1.2.0 released
