### ISSUE TITLE
Add support for Gx instances

### ISSUE THREAD

**Issue by joaquincasares** [MSOpenTech/vagrant-azure#77]
I found this commit being applied to the azure-sdk-for-ruby project:

https://github.com/Azure/azure-sdk-for-ruby/commit/25559310960a914ea30c6342235f92261ad5955d

However, it doesn't seem to be in the 0.6.4 nor 0.6.5 release. Can you add a monkeypatch for additional vm_size support?

I'm currently building out the infrastructure for a demo that will be shown at Build 2015 at the end of April and would be nice to have the correct instances supported by then.

Thanks again!

**Comment by devigned** [comment]
I think there will be a new release of the ruby sdk shortly. There have been quite a few desirable changes over the past few weeks. I'll leave this open until the new rev is released and this project is upgraded.

**Comment by joaquincasares** [comment]
Great, sounds good! Thanks for the update!

**Comment by devigned** [comment]
This should be good in master. Grab that latest bits and give it a go.
