### ISSUE TITLE
Provisioning multiple times

### ISSUE THREAD

**Issue by joaquincasares** [MSOpenTech/vagrant-azure#84]
When I run a similar command:
    vagrant up --provider azure node1 node2

where the only thing node1 and node2 execute is:
    config.vm.provision 'shell', inline: "echo GATHER_IPS $(hostname -i)"

I see multiple outputs where I'm expecting only one per machine.

I do, however, have a larger project with multiple machines and if statements and the above is only a distilled example. I'll try distilling this in a separate repo soon, but figured this should be enough to start investigating and tracking.

**Comment by devigned** [comment]
please provide a gist or something to help repo. I'm happy to take a look and fix if needed.

**Comment by joaquincasares** [comment]
I'm closing this issue since I found this to not be Azure specific, but instead specific to Vagrant and have filed a ticket here:

https://github.com/mitchellh/vagrant/issues/5778

Thanks for your attention!
