### ISSUE TITLE
Vagrant up > loop "looking for local port 22"

### ISSUE THREAD

**Issue by ebuildy** [MSOpenTech/vagrant-azure#86]
Running a "vagrant up", everything is OK (cloud & VM are created), but Vagrant is looping to port sequence:

https://beemapp.s3.amazonaws.com/14b4678f-55e8-4cf2-b872-5b2a1d6e5633.jpg

Here my Vagrant file:

https://gist.github.com/ebuildy/426fd26446422977f50e

Am I wrong somewhere?

Thanks,

**Comment by aabdulwahed** [comment]
I got the same issue, did you solve it ?

**Comment by mvanderkroon** [comment]
Same here, anyone any luck?

**Comment by aabdulwahed** [comment]
yes, It is solved, here is my Vagrant file that works 
  
**Vagrantfile**
   
     ............
     config.vm.define 'slave2' do |cfg|
       cfg.vm.provider :azure do |azure, override|
         common_azure.call azure, override
         azure.vm_name = 'secondary-node2'
         azure.ssh_port = 2202
         azure.tcp_endpoints = '40002:40002,40001:30100, 40000:30400'
       end
     end
    # AFTER ADDING THE FOLLOWING 2 LINES
    config.ssh.username = 'ahmed' # modify this username
    config.ssh.private_key_path = "/home/ubuntu/.ssh/id_rsa" # modify this path 
    end

**Comment by RTL-Nederland** [comment]
Thanks for sharing, unfortunately the fix doesn't seem to work for me. I still enter the loop. If I end up finding a solution I'll be sure to post it here.

**Comment by aabdulwahed** [comment]
can you try this Vagrant sample file

https://github.com/aabdulwahed/MongoDB-Azure-Ansible/blob/master/Vagrantfile

**Comment by RTL-Nederland** [comment]
gets stuck on exactly the same point (after emitting "<nodename> Add Role? - false")

![vagrant](https://cloud.githubusercontent.com/assets/12035527/8540205/89d8c3d2-2483-11e5-9c8d-92e06fc7003a.PNG)

**Comment by ebuildy** [comment]
I ended up to move to Amazon ;-) I lost too many time on Azure, it just never work. 

Took me 5 minutes on AWS whereas I could lost days on Azure, no way.

**Comment by rocket-ron** [comment]
I have spent 2 days trying various combinations of settings for SSH keys and Linux OS'es and I can't get away from the Looking for local port 22, Found port mapping 22 --> 22 loop. As a result I'm unable to provision the azure vm.

Currently my settings look like:

    config.vm.box = "azure"
    config.vm.boot_timeout = 1000

    config.vm.provider :azure do |azure, override|
      azure.mgmt_certificate = '***************************'
      azure.mgmt_endpoint = 'https://management.core.windows.net'
      azure.subscription_id = '**************************'
      azure.storage_acct_name = '*****************' # optional. A new one will be generated if not provided.

      azure.vm_image = '0b11de9248dd4d87b18621318e037d37__RightImage-CentOS-6.5-x64-v14.1.5.1'
      azure.vm_user = 'rcordell'
        azure.ssh_private_key_file = File.expand_path('/home/rcordell/.ssh/azurekey.pem')
        azure.ssh_certificate_file = File.expand_path('/home/rcordell/.ssh/azurekey.key')

      azure.vm_name = 'mckrhcea01-mgo2' # max 15 characters. contains letters, number and hyphens. can start with letters and can end with letters and numbers
      azure.cloud_service_name = 'mckrhcea01-mgo2' # same as vm_name. leave blank to auto-generate
      azure.deployment_name = 'mckrhcea01-mgo2' # defaults to cloud_service_name
      azure.vm_location = 'West US' # e.g., West US
      azure.private_key_file = '/Users/rcordell/.ssh/azurekey.key'
      azure.certificate_file = '/Users/rcordell/.ssh/azurekey.pem'

      # Provide the following values if creating a *Nix VM
      azure.ssh_port = '22'
      config.vm.provision :shell, :path => "../puppet/bootstrap/centos_6_x.sh"

      config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "../puppet/manifests"
        puppet.module_path = "../puppet/modules"
        puppet.options = ['--verbose']
      end

    end

  config.ssh.username = 'rcordell' # the one used to create the VM
  config.ssh.private_key_path = File.expand_path('~/.ssh/azurekey.pem') 

But every time I get:

  ==> default: Machine reached state ReadyRole
  ==> default: VM 'mckrhcea01-mgo2' has been started
  ==> default: Waiting for Communication
  ==> default: Looking for local port 22
  ==> default: Found port mapping 22 --> 22
  ==> default: Looking for local port 22
  ==> default: Found port mapping 22 --> 22
  ==> default: Looking for local port 22
  ==> default: Found port mapping 22 --> 22
  ==> default: Looking for local port 22
  ==> default: Found port mapping 22 --> 22

I'm not clear on the various ssh key and cert paths and parameters. I've got three places where SSH keys are referenced, but are these paths all local or are some of them for the remote VM?

**Comment by rocket-ron** [comment]
I think I got the looping problem fixed. Here's what I ended up with in the Vagrantfile (excerpted):

    config.vm.box = "azure"
    config.vm.boot_timeout = 1000

    config.vm.provider :azure do |azure, override|
      azure.mgmt_certificate = '*******************************'
      azure.mgmt_endpoint = 'https://management.core.windows.net'
      azure.subscription_id = '********************************'
      azure.storage_acct_name = '***********************' 

      azure.vm_image = 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_5-LTS-amd64-server-20150707-en-us-30GB'
      azure.vm_user = 'rcordell'
        azure.ssh_private_key_file = File.expand_path('~/.ssh/id_rsa')  # This is my private SSH key
        azure.ssh_certificate_file = File.expand_path('~/.ssh/ssh-cert.pem')  # This is the X509 certificate file generated from my private SSH key

      azure.vm_name = '**************' # max 15 characters. contains letters, number and hyphens. can start with letters and can end with letters and numbers
      azure.cloud_service_name = '***************' # same as vm_name. leave blank to auto-generate
      azure.deployment_name = '****************' # defaults to cloud_service_name
      azure.vm_location = 'West US' # e.g., West US

      # Provide the following values if creating a *Nix VM
      azure.ssh_port = '22'
      config.vm.provision :shell, :path => "../puppet/bootstrap/ubuntu.sh"

      config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "../puppet/manifests"
        puppet.module_path = "../puppet/modules"
        puppet.options = ['--verbose']
      end

    end

  config.ssh.username = 'rcordell' # the one used to create the VM
  config.ssh.private_key_path = File.expand_path('~/.ssh/id_rsa') # this is my private SSH to use instead of the Vagrant insecure key

Once I got the SSH keys and certificates straightened out, the SSH port looping went away, and I'm able to vagrant ssh to the box as expect. However, the rsync stuff is broken as I now get this error:

    ==> default: VM Status: ReadyRole
    No host IP was given to the Vagrant core NFS helper. This is
    an internal error that should be reported as a bug.

I'll pursue that problem in a different thread/issue. I realize there are vagrant issue topics on this error as well and I'll take a deeper look at them.

**Comment by aabdulwahed** [comment]
@rocket-ron  I have the same issue

**Comment by devigned** [comment]
I ran through the provisioning and cert related issues and added to the readme some clarification on how this functions. It's also updated to the latest azure ruby sdk. Please check out the changes in master and let me know if this helps.

Per the NFS issue, that is delegated down to vagrant proper. If you are having issues with it try using rsync rathe than nfs.

**Comment by devigned** [comment]
Give this a try w/ v1.2.0. This should be fixed. Reopen if still an issue.
