### ISSUE TITLE
Add vm_size to the example config in readme

### ISSUE THREAD

**Issue by worldspawn** [MSOpenTech/vagrant-azure#87]
I had to google around to see that people were setting values like "Small", "ExtraSmall" etc to the vm_size config option, could the readme include some info about possible values and how they relate to the labels that people actually see in the portal ui (A0, A1) etc.

I up'd a test vagrant file which didn't specify the vm_size, i ended up with a a1 standard vm. I then added a vm_size option to my vagrant file `azure.vm_size = "Large"` and then ran `vagrant reload` which the docs say I should run when i change the VagrantFile. However the recreated vm is still A1. What am I doing wrong?

Also is there an option to set the tier (basic/standard)?

**Comment by worldspawn** [comment]
Destroying and up'ing again yielded the correct instance size, is that the only way to change size (with vagrant)?

Also destroying did not remove the storage it had previously provisioned.

**Comment by digitaldrummerj** [comment]
Here is an Azure SDK powershell script that I use to get the list of possible VM sizes by location.  It outputs the location name and a comma delimited list of possible sizes.  

https://gist.github.com/digitaldrummerj/be3eb227be0330867b18

**Comment by devigned** [comment]
Yes, you will have to destroy and then rebuild. This would be a good feature to add and would happy to review a pull request.
