### ISSUE TITLE
Better documentation for certification stuff and Azure

### ISSUE THREAD

**Issue by pawelsawicz** [MSOpenTech/vagrant-azure#88]
Unfortunately it not readable at all :(

Going to add some more explanation about providing certificates, because it's big pain right now.
[related problem](https://github.com/MSOpenTech/vagrant-azure/issues/25#issuecomment-114315592)

started my work [here](https://github.com/pawelsawicz/vagrant-azure/tree/update-readme-certificates)

**Comment by devigned** [comment]
@pawelsawicz do you think [this documentation](https://github.com/Azure/azure-sdk-for-ruby#get-started-with-publish-settings) is more helpful for dealing with publish settings? 

The pfxer was recently added to the azure ruby sdk to help move from publish settings to pfx files. Also, file and string format are supported in the master branch of the azure ruby sdk. I just haven't had the time to update vagrant-azure to take advantage of these improvements.

**Comment by pawelsawicz** [comment]
@devigned sorry for late response was away, before I do any work I just wanted to pointed out few things and make sure that I am not wrong.

1. When ```azure.cloud_service_name``` is blank then we shouldn't provide in our vagrantfile ```azure.deployment_name.```
2. You can either [have](https://github.com/pawelsawicz/vagrant-dontstarve/blob/master/Vagrantfile#L18) ```azure.private_key_file``` or ```azure.certificate_file```
3. Certification section seems to be OK, I got confused because I on Azure portal you have to upload `*.cer` file where at vagrantfile you have to provide PEM by OpenSSL ```openssl pkcs12 -in vagrant.pfx -out c.pem -nodes```
4. I couldn't replicate PEM generation section.

Let me know if those points are helpful and I will start work.
