### ISSUE TITLE
Attache Second HD to Running VM on Azure

### ISSUE THREAD

**Issue by aabdulwahed** [MSOpenTech/vagrant-azure#89]
Hi, 
How can I attach an extra Hard disk using vagrant to a running virtual machine on Windows Azure, I read your documentation but I can not find anything about.

thanks
Ahmed

**Comment by devigned** [comment]
It is not implemented yet in this repo, but it's available with the azure ruby sdk. If you would like to submit a pull request, I'd love to get this pulled in.

**Comment by aabdulwahed** [comment]
Yes, please share the link of repo 

Thanks
Ahmed

**Comment by devigned** [comment]
Not just a link to the repo, but the method to call :boom:! https://github.com/Azure/azure-sdk-for-ruby/blob/master/lib/azure/virtual_machine_management/virtual_machine_management_service.rb#L447

Thank you for your interest. Let me know if you have any questions.

**Comment by devigned** [comment]
dup of #81
